### ISSUE TITLE
Boat ship

### ISSUE THREAD

**Issue by Cmoen11** [Cmoen11/IS-105_2016_Gruppe-2-#38]
Noe som bør ses på ved boatship

Klasser:
river arver fra en superklasse

Metoder: 
view
climb out
climb in
step
transduce
run

**Comment by uia-worker** [comment]
Hei, så på deres klasser og dette er slik jeg ser på det: Vær OBS på å ikke fokusere på entiteter i første omgang. Fokuser og beskriv detaljert alle mulige tilstander i "verden". Bruk skisser, tabeller tekst for å lage en grunnleggende problemanalyse før dere skriver kode. Se e-posten fra torsdagskveld (2016-03-03).
